baseURL = "https://euxn.me/"
languageCode = "en-us"
title = "EUXN.ME"
theme = "hugo-identity-theme"

disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]


[params]
favicon_ico = "favicon.ico"
favicon_ico_sizes = "16x16 32x32"
favicon_png = "favicon.png"
favicon_png_sizes = "16x16 32x32"

[params.footer]
copyright = "euxn.me"


[params.personal]
name = "EUXN (YUTASZK)"
avatar = "icon.png"
position = "Software Engineer / Web Engineer"
livesIn = "[Nerima, Tokyo]"
scope = [
  "Using: js, ts, go, py, rb",
  "Learning: scala, hs, rs",
  "Used: java, php",
]
biography = """
@euxn《ゆん》 a.k.a. @yutaszk。本名、鈴木雄大。
<br>
1992年茨城県農家生まれ農家育ち。ダイヤルアップ時代にインターネットを始める。
<br>
経済学部に入学後、機会に恵まれ Java と Ruby を主に学び、エンジニアとして就職。
<br>
フロントエンドの SPA や、サーバサイドの WebAPI を中心に開発。
<br>
ミドルウェアや仮想インフラも少々。自作 PC や自宅鯖も。自動化やツール開発も好む。
<br>
最近は GitLab Issue Board のクライアント開発、ダンジョン探索ブラウザゲーム開発をしている。
"""

[[params.social]]
title = "GitHub"
icon = "fa-github"
link = "https://github.com/yutaszk"

[[params.social]]
title = "Eutech Blog"
icon = "fa-book"
link = "https://blog.euxn.me/"

[[params.social]]
title = "qiita"
icon = "fa-search"
link = "http://qiita.com/yutaszk"

[[params.social]]
title = "Hatena Bookmark"
icon = "fa-bookmark"
link = "http://b.hatena.ne.jp/yutaszk23/bookmark"

[[params.social]]
title = "Facebook"
icon = "fa-facebook"
link = "https://facebook.com/yutaszk"

[[params.social]]
title = "Twitter"
icon = "fa-twitter"
link = "https://twitter.com/euxn23"
